markdown: kramdown
highlighter: rouge
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

url: http://guillermo.in
baseurl: /exceptions4c
repository: https://github.com/guillermocalvo/exceptions4c/
help_url: https://github.com/guillermocalvo/exceptions4c/wiki/

collections:
  docs:
    output: true

exclude: ["README.md"]

google_analytics_id: UA-61670496-1
